env:
  node: true
  es2021: true
plugins: [fp]
extends: [airbnb-base, plugin:jest/recommended]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
  import/extensions: 0,
  fp/no-mutating-methods: [error, {
    "allowedObjects": ['_']
  }]
}
